stages:
  - package
  - docker_build
  - deploy_k8s
server_install:
  image: node:12
  stage: package
  tags:
    - release
  script:
    - cd frontend
    - npm  i --registry  https://registry.npmmirror.com/
    - npx vue-cli-service build
    - tar -cvf  release.tar.gz ./dist
  cache:
    key: 'frontend'
    paths:
      - frontend/node_modules
      - frontend/release.tar.gz
    policy: push

docker_build_job:
  image: docker:latest
  stage: docker_build
  tags:
    - release
  cache:
    key: 'frontend'
    paths:
      - frontend/node_modules
      - frontend/release.tar.gz
    policy: pull
  script:
    - docker build --tag registry.docker.cooper.com:5000/cooper_base ./frontend
    - docker push registry.docker.cooper.com:5000/cooper_base
