stages:
  - package
  - docker_build
  - deploy_k8s
server_install:
  image: node:12
  stage: package
  tags:
    - release
  script:
    - cd frontend
    - npm  i --registry  https://registry.npmmirror.com/
    - npx vue-cli-service build
  cache:
    key: 'frontend_module'
    paths:
      - frontend/node_modules
docker_build_job:
  image: docker:latest
  stage: docker_build
  tags:
    - release
  script:
    - docker
#deploy_k8s_job:
#  image: registry.cn-hangzhou.aliyuncs.com/haoshuwei24/kubectl:1.16.6
#  stage: deploy_k8s
#  tags:
#    - k8s-runner
#  script:
#    - mkdir -p /etc/deploy
#    - echo $kube_config |base64 -d > $KUBECONFIG
#    - sed -i "s/IMAGE_TAG/$CI_PIPELINE_ID/g" deployment.yaml
#    - cat deployment.yaml
#    - kubectl apply -f deployment.yaml
